Updates for WCAG 2.2
w3c/wai-wcag-em-report-tool pull request #132
Opened 2023-11-10 10:55 UTC by iadawn

2023-11-11 09:13 UTC, rvantonisse commented
Looks good! Lot of folks are going to like this. 😄

2023-12-06 16:24 UTC, iadawn commented
@shawna-slh Ready for publication

2023-12-06 17:13 UTC, remibetin requested changes

2023-12-06 17:24 UTC, shawna-slh commented on src/components/ui/Auditor/Criterion.svelte
> +        href="https://www.w3.org/WAI/WCAG{wcagVersion}/Understanding/{id}.html"
@iadawn , those aren't the ones you were thinking of deleting though?

2023-12-06 17:24 UTC, remibetin requested changes

2023-12-06 17:24 UTC, remibetin commented on src/components/ui/Auditor/Criterion.svelte
> +        href="https://www.w3.org/WAI/WCAG{wcagVersion}/Understanding/{id}.html"
@iadawn When I choose "WCAG 2.0", "Understanding 1.1.1" link points to https://www.w3.org/WAI/WCAG20/Understanding/text-equiv-all.html and does not work.

https://www.w3.org/TR/UNDERSTANDING-WCAG20/text-equiv-all.html is working though.

When I choose "WCAG 2.1", Understanding 1.1.1." link points to https://www.w3.org/WAI/WCAG21/Understanding/non-text-content.html and does work

2023-12-06 17:47 UTC, remibetin commented
@shawna-slh 

This PR and https://github.com/w3c/wai-wcag-em-report-tool/pull/127 can not be deployed together as they are.

To not break the French translation, new WCAG 2.2. SCs will need to be added to the French version of `wcag.json`.

If French translation is merged before WCAG 2.2.: to add in this PR.
If WCAG 2.2. is merged before French translation: to add in https://github.com/w3c/wai-wcag-em-report-tool/pull/127

2023-12-06 17:50 UTC, iadawn commented
So, publish this PR so that 2.2 is supported in EM Report tool. Then update and publish #127 to provide the French translation?

2023-12-11 15:38 UTC, shawna-slh commented
> To not break the French translation, new WCAG 2.2. SCs will need to be added (untranslated) to the French version of wcag.json.

What about not breaking other translations? Other one on our website is Nederlands. They are in same situation that 2.2 authorized translation is in progress.

Lower priority maybe we want to provide guidance to those who have forked and have localized version?

2023-12-11 15:57 UTC, remibetin commented on src/locales/nl/WCAG.json
> +        },
I have opened an issue for this: https://github.com/w3c/wai-wcag-em-report-tool/issues/139

2023-12-11 16:07 UTC, shawna-slh commented
Kevin OKed ready to publish (verbally in meeting now :)

2023-12-11 16:07 UTC, merged